[sdl]
fullscreen=true
fullresolution=desktop
output=opengl

[render]
scaler=none
aspect=true

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cputype=auto
cycles=max

[mixer]
rate=44100
blocksize=1024

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[dos]
keyboardlayout=il

[autoexec]
@echo off
mount c game
mount d game/cd
c:
cd \installed
ALEX1.EXE
