#!/usr/bin/env python3
"""Generate remake prison text data from the original PRISON.SCX."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "re" / "formats"))

from parse_scx import parse_file  # type: ignore

SRC = ROOT / "game_decrypted" / "cd" / "PRISON.SCX"
OUT = ROOT / "remake" / "src" / "scenes" / "prison" / "generated" / "prison-text.js"


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    messages = {}
    for section in parse_file(str(SRC)):
        head = section["id"].split(",")[0]
        if not head.isdigit():
            continue
        section_id = int(head)
        if 500 <= section_id < 600:
            messages[str(section_id)] = {
                "header": section["id"],
                "lines": section["lines"],
            }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by remake/tools/generate_prison_text_module.py from game_decrypted/cd/PRISON.SCX\n"
        f"export const PRISON_TEXT = Object.freeze({js({'messages': messages})});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
