#!/usr/bin/env python3
"""Generate remake airport physical world data from the original ALEX1.OVR."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "re"))

from extract_hotspots import extract_all_scenes  # type: ignore

SRC = ROOT / "game_decrypted" / "cd" / "ALEX1.OVR"
OUT = ROOT / "remake" / "src" / "scenes" / "airport" / "generated" / "airport-world.js"


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    scenes, _scene_table = extract_all_scenes(str(SRC))
    scene = next((entry for entry in scenes if entry.get("scene") == "Airport"), None)
    if scene is None:
        raise SystemExit("Airport scene not found in ALEX1.OVR")

    world = {
        "objects": [{k: v for k, v in obj.items() if k != "offset"} for obj in scene["objects"]],
        "namedHotspots": [{k: v for k, v in hs.items() if k != "offset"} for hs in scene["hotspots"]],
        "clickRects": [{k: v for k, v in rect.items() if k != "offset"} for rect in scene["click_rects"]],
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by remake/tools/generate_airport_world_module.py from game_decrypted/cd/ALEX1.OVR\n"
        f"export const AIRPORT_WORLD = Object.freeze({js(world)});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
