#!/usr/bin/env python3
"""Generate airport text data for the remake directly from AIRPORT.SCX."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "re" / "formats"))

from parse_scx import parse_file  # type: ignore

SRC = ROOT / "game_decrypted" / "cd" / "AIRPORT.SCX"
OUT = ROOT / "remake" / "src" / "scenes" / "scripts" / "generated" / "airport-text.js"


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    sections = {}
    for section in parse_file(str(SRC)):
      head = section["id"].split(",")[0]
      if head.isdigit():
          sections[int(head)] = section["lines"]

    dialog_ids = [2010, 2100]
    message_ids = [1021, 1022, 1023, 1024, 1031, 1080, 1081, 1082, 1191, 1192, 1193]

    dialogs = {str(section_id): sections[section_id] for section_id in dialog_ids}
    messages = {str(section_id): sections[section_id] for section_id in message_ids}

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by re/generate_airport_text_module.py from game_decrypted/cd/AIRPORT.SCX\n"
        f"export const AIRPORT_TEXT = Object.freeze({js({'dialogs': dialogs, 'messages': messages})});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
