#!/usr/bin/env python3
"""Generate remake StripAir physical world data from the original ALEX1.OVR."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "re"))

from extract_hotspots import (  # type: ignore
    extract_click_rects,
    extract_hotspots,
    extract_object_properties,
    extract_objects,
)

SRC = ROOT / "game_decrypted" / "cd" / "ALEX1.OVR"
OUT = ROOT / "remake" / "src" / "scenes" / "stripair" / "generated" / "stripair-world.js"
FUNC_START = 0x25498
FUNC_END = 0x25E23
CS_BASE = 0x252BD


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    data = SRC.read_bytes()
    world = {
        "objects": [{k: v for k, v in obj.items() if k != "offset"} for obj in extract_objects(data, FUNC_START, FUNC_END, CS_BASE)],
        "objectProperties": [{k: v for k, v in prop.items() if k != "offset"} for prop in extract_object_properties(data, FUNC_START, FUNC_END)],
        "namedHotspots": [{k: v for k, v in hs.items() if k != "offset"} for hs in extract_hotspots(data, FUNC_START, FUNC_END, CS_BASE)],
        "clickRects": [{k: v for k, v in rect.items() if k != "offset"} for rect in extract_click_rects(data, FUNC_START, FUNC_END, CS_BASE)],
        "functionOffset": FUNC_START,
        "functionEnd": FUNC_END,
        "csBase": CS_BASE,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by tools/generate_stripair_world_module.py from game_decrypted/cd/ALEX1.OVR\n"
        f"export const STRIPAIR_WORLD = Object.freeze({js(world)});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
