#!/usr/bin/env python3
"""Generate remake GLOBAL text data from the original GLOBAL.SCX."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "re" / "formats"))

from parse_scx import parse_file  # type: ignore

SRC = ROOT / "game_decrypted" / "cd" / "GLOBAL.SCX"
OUT = ROOT / "remake" / "src" / "runtime" / "generated" / "global-text.js"


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    text_refs = {}
    for section in parse_file(str(SRC)):
        head = section["id"].split(",")[0]
        if not head.isdigit():
            continue
        section_id = int(head)
        if section_id < 10000:
            continue
        text_refs[str(section_id)] = {
            "header": section["id"],
            "lines": section["lines"],
        }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by tools/generate_global_text_module.py from game_decrypted/cd/GLOBAL.SCX\n"
        f"export const GLOBAL_TEXT = Object.freeze({js({'textRefs': text_refs, 'dialogs': {}, 'messages': {}})});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
