#!/usr/bin/env python3
"""Generate remake airport text data from the original AIRPORT.SCX."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "re" / "formats"))

from parse_scx import parse_file  # type: ignore

SRC = ROOT / "game_decrypted" / "cd" / "AIRPORT.SCX"
OUT = ROOT / "remake" / "src" / "scenes" / "airport" / "generated" / "airport-text.js"


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    sections = {}
    for section in parse_file(str(SRC)):
        head = section["id"].split(",")[0]
        if head.isdigit():
            sections[int(head)] = section["lines"]

    dialog_ids = [section_id for section_id in sections if 2000 <= section_id < 3000]
    text_ref_ids = [section_id for section_id in sections if 500 <= section_id < 1000]
    message_ids = [section_id for section_id in sections if 1000 <= section_id < 1300]

    dialogs = {str(section_id): sections[section_id] for section_id in dialog_ids}
    text_refs = {str(section_id): sections[section_id] for section_id in text_ref_ids}
    messages = {str(section_id): sections[section_id] for section_id in message_ids}

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by tools/generate_airport_text_module.py from game_decrypted/cd/AIRPORT.SCX\n"
        f"export const AIRPORT_TEXT = Object.freeze({js({'textRefs': text_refs, 'dialogs': dialogs, 'messages': messages})});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
